#!/bin/bash

# pre-new --- Notmuch rules that run before notmuch new
#
# Copyright (c) 2021-2024  Protesilaos Stavrou <info@protesilaos.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
## Commentary:
#
# Move unwanted email to the appropriate local directory and tag it
# accordingly.  The order of those commands matters.
#
# Part of my dotfiles: <https://github.com/protesilaos/dotfiles>.

if [ "$HOSTNAME" = "kronos" ]
then
    mail_root_path=$(notmuch config get database.path)
    for tag in del spam
    do
        target_directory="${mail_root_path}/${tag}local/"

        if [ ! -d "$target_directory" ]
        then
            mkdir -p "$target_directory"
        fi

        while IFS= read -r -d $'\0' file
        do
            if [ -f "$file" ]
            then
                mv "$file" "$target_directory$(basename -- "${file//,U=[0-9]*:/:}")"
            fi
        done < <(notmuch search --output=files --format=text0 tag:"$tag")

        notmuch tag -inbox -"${tag}" +"${tag}"local -- tag:"$tag"
    done
fi
